
project_id = "afkkhmzpchftivvqkejg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
port = 54325

[functions]
[functions.send-workout-sms]
verify_jwt = true
